"""update feedback table

Revision ID: afd0734b52ee
Revises: d36acb9d93e9
Create Date: 2024-10-09 22:49:57.064161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd0734b52ee'
down_revision: Union[str, None] = 'd36acb9d93e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'message')
    # ### end Alembic commands ###
